# ==========================================
# SERVER
# ==========================================

server.port=8080

spring.application.name=nexcure-backend


# ==========================================
# GROQ API
# ==========================================

groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=openai/gpt-oss-120b


# ==========================================
# SUPABASE / POSTGRESQL
# ==========================================

spring.datasource.url=jdbc:postgresql://db.vrhpdbpzyicgdgaargyp.supabase.co:5432/postgres?sslmode=require

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=postgres

spring.datasource.password=abhishek@#88AA


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false


# ==========================================
# FIREBASE AUTH
# ==========================================

firebase.project-id=resqlink-67dda
firebase.client-email=firebase-adminsdk-fbsvc@resqlink-67dda.iam.gserviceaccount.com
firebase.private-key=MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCzKsCzrnKdZQY3


# ==========================================
# CORS
# ==========================================

app.cors.allowed-origins=${CLIENT_URL:http://localhost:3000}
